"""Add patient table and link to users

Revision ID: 167610f22495
Revises: c8595dd2ff6c
Create Date: 2025-08-20 11:03:49.482550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167610f22495'
down_revision = 'c8595dd2ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('date_of_birth', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('presenting_problem', sa.Text(), nullable=True),
    sa.Column('billing_type', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
