"""added meeting model

Revision ID: 72da0af15385
Revises: ba945bf8a77d
Create Date: 2025-09-02 18:30:10.097060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72da0af15385'
down_revision = 'ba945bf8a77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('meet_link', sa.String(length=512), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###
