"""Add doctor profile model and relationship

Revision ID: f9998696a421
Revises: c8595dd2ff6c
Create Date: 2025-08-19 15:41:45.991921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9998696a421'
down_revision = 'c8595dd2ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('medical_license_number', sa.String(length=255), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=False),
    sa.Column('npi_number', sa.String(length=255), nullable=True),
    sa.Column('dea_number', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=512), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('languages_spoken', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('available_for_telehealth', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dea_number'),
    sa.UniqueConstraint('medical_license_number'),
    sa.UniqueConstraint('npi_number'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
